In [24]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

In [25]:
df=pd.read_csv("Refprices.csv") #Read Refprice csv file
print(df.head())

   Unnamed: 0        Date          RowId  SecuritiesCode    Open    High  \
0     2472412  2022-03-18  20220318_9531            9531  2308.0  2333.0   
1     2472413  2022-03-18  20220318_9532            9532  2157.0  2183.0   
2     2472414  2022-03-18  20220318_9533            9533  2786.0  2846.0   
3     2472415  2022-03-18  20220318_9534            9534  1509.0  1512.0   
4     2472416  2022-03-18  20220318_9535            9535   345.0   346.0   

      Low   Close   Volume  AdjustmentFactor  ExpectedDividend  \
0  2250.0  2252.0  3407000               1.0               NaN   
1  2105.0  2116.0  2260800               1.0               NaN   
2  2730.0  2758.0   507900               1.0               NaN   
3  1500.0  1500.0    31100               1.0               NaN   
4   339.0   344.0   245500               1.0               NaN   

   SupervisionFlag  
0            False  
1            False  
2            False  
3            False  
4            False  


In [3]:
print(df.shape) #shap of pandas data frame

(130000, 12)


In [4]:
df.isna().any() # That's true any one data point missing in the column.

Unnamed: 0          False
Date                False
RowId               False
SecuritiesCode      False
Open                 True
High                 True
Low                  True
Close                True
Volume              False
AdjustmentFactor    False
ExpectedDividend     True
SupervisionFlag     False
dtype: bool

In [5]:
df.isna().sum()/len(df) # As a presentage

Unnamed: 0          0.000000
Date                0.000000
RowId               0.000000
SecuritiesCode      0.000000
Open                0.003315
High                0.003315
Low                 0.003315
Close               0.003315
Volume              0.000000
AdjustmentFactor    0.000000
ExpectedDividend    0.988446
SupervisionFlag     0.000000
dtype: float64

In [26]:
df.drop('ExpectedDividend',axis=1,inplace=True) #remove ExpectedDivided colum because many datas missing

In [7]:
df.head()

Unnamed: 0        Date          RowId  SecuritiesCode    Open    High  \
0     2472412  2022-03-18  20220318_9531            9531  2308.0  2333.0   
1     2472413  2022-03-18  20220318_9532            9532  2157.0  2183.0   
2     2472414  2022-03-18  20220318_9533            9533  2786.0  2846.0   
3     2472415  2022-03-18  20220318_9534            9534  1509.0  1512.0   
4     2472416  2022-03-18  20220318_9535            9535   345.0   346.0   

      Low   Close   Volume  AdjustmentFactor  SupervisionFlag  
0  2250.0  2252.0  3407000               1.0            False  
1  2105.0  2116.0  2260800               1.0            False  
2  2730.0  2758.0   507900               1.0            False  
3  1500.0  1500.0    31100               1.0            False  
4   339.0   344.0   245500               1.0            False

In [27]:
df.isna().sum() #How many data paint missing in colum of DF

Unnamed: 0            0
Date                  0
RowId                 0
SecuritiesCode        0
Open                431
High                431
Low                 431
Close               431
Volume                0
AdjustmentFactor      0
SupervisionFlag       0
dtype: int64

In [28]:
df.isna().any(axis=1).sum() #How many data missing raws

431

In [29]:
df.dropna(how='any',inplace=True) #Remove data missing raws

In [30]:
df.isna().any(axis=1).sum()

0

In [31]:
df.shape

(129569, 11)

In [42]:
SecuritiesCategory=df['SecuritiesCode']

In [44]:
from sklearn.preprocessing import LabelEncoder
obj=LabelEncoder()
Securities=obj.fit_transform(SecuritiesCategory)

In [47]:
Securities

array([1881, 1882, 1883, ..., 1997, 1998, 1999], dtype=int64)

In [48]:
from sklearn.preprocessing import LabelBinarizer
obj=LabelBinarizer()
Securities=obj.fit_transform(SecuritiesCategory)

In [49]:
Securities

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 1]])

In [52]:
obj.classes_ #One Hot Encoded data(SecuritiesCode)

array([1301, 1332, 1333, ..., 9993, 9994, 9997], dtype=int64)

In [32]:
x1=df.iloc[:,4:5].values
x2=df.iloc[:,5:6].values
x3=df.iloc[:,6:7].values
x4=df.iloc[:,7:8].values

In [33]:
x1

array([[2308.],
       [2157.],
       [2786.],
       ...,
       [1548.],
       [2507.],
       [ 710.]])

In [34]:
x2

array([[2333.],
       [2183.],
       [2846.],
       ...,
       [1548.],
       [2527.],
       [ 725.]])

In [35]:
x3

array([[2250.],
       [2105.],
       [2730.],
       ...,
       [1497.],
       [2498.],
       [ 710.]])

In [36]:
x4

array([[2252.],
       [2116.],
       [2758.],
       ...,
       [1497.],
       [2527.],
       [ 719.]])

In [37]:
#Normalizing the Dataset
scaler=MinMaxScaler(feature_range=(0,1)) 
scaler_train_set1=scaler.fit_transform(x1)
scaler_train_set2=scaler.fit_transform(x2)
scaler_train_set3=scaler.fit_transform(x3)
scaler_train_set4=scaler.fit_transform(x4)

In [16]:
scaler_train_set1

array([[0.03155198],
       [0.02944944],
       [0.03820769],
       ...,
       [0.02096967],
       [0.03432287],
       [0.00930129]])

In [17]:
scaler_train_set2

array([[0.03175836],
       [0.02967812],
       [0.03887279],
       ...,
       [0.02087176],
       [0.03444881],
       [0.00945817]])

In [18]:
scaler_train_set3

array([[0.0312363 ],
       [0.02918593],
       [0.03802373],
       ...,
       [0.02058853],
       [0.03474314],
       [0.00945998]])

In [19]:
scaler_train_set4

array([[0.03101841],
       [0.02910959],
       [0.03812037],
       ...,
       [0.02042163],
       [0.03487817],
       [0.00950202]])

In [38]:
scaler_train_set4.shape

(129569, 1)

In [39]:
X1_train = []
y1_train = []
for i in range(60, 129569):
    X1_train.append(scaler_train_set1[i-60:i, 0])
    y1_train.append(scaler_train_set1[i, 0])
X1_train, y1_train = np.array(X1_train), np.array(y1_train)

X1_train = np.reshape(X1_train, (X1_train.shape[0], X1_train.shape[1], 1))